name:  CICD

on:
  push:
    branches:
      - main
    # paths:
    #   - '.'
  pull_request:
    branches: [ "main" ]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      run: |
        COMMIT_SHA=${{ github.sha }}
        DATE=$(date +'%Y%m%d')
        IMAGE_TAG="${{ env.DOCKER_HUB_USER }}/chatapp-frontend:${COMMIT_SHA}-${DATE}"
        docker build . -t $IMAGE_TAG
        docker push $IMAGE_TAG