name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
      branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test

  publish_images:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        COMMIT_SHA=${{ github.sha }}
        DATE=$(date +'%Y%m%d')
        IMAGE_TAG="maverick0809/chatapp-frontend:${COMMIT_SHA}-${DATE}"
        docker build . -t $IMAGE_TAG
        docker push $IMAGE_TAG